name: seasnap-de-p311
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9,<3.12
  - snakemake=7.19
  - r-base>=4.1
  - bioconductor-deseq2=1.38
  - bioconductor-genomicfeatures
  - bioconductor-annotationdbi
  - bioconductor-org.hs.eg.db # annotation for human
  - bioconductor-org.Mm.eg.db # annotation for mouse
  - bioconductor-tximport
  - bioconductor-goseq
  - bioconductor-apeglm
  - bioconductor-biomart
  - bioconductor-enrichplot
  - bioconductor-clusterprofiler
  - bioconductor-go.db
  - bioconductor-limma
  - bioconductor-rsamtools
  - bioconductor-rsubread
  - bioconductor-rtracklayer
  - r-blob
  - r-cairo
  - r-cowplot
  - r-crayon
  - r-devtools
  - r-ggplot2
  - r-ggrepel
  - r-ggplotify
  - r-readr
  - r-readxl
  - r-writexl
  - r-roxygen2
  - r-tidyr
  - r-tidyselect
  - r-testthat
  - r-remotes
  - r-ashr
  - r-pheatmap
  - r-shiny
  - r-msigdbr>=7.4
  - r-dplyr
  - r-biocmanager
  - r-xml2
  - r-xopen
  - r-tmod>=0.50.11
# Required for the actual report
  - r-dt
  - r-purrr
  - r-plotly
  - r-pander
  - bioconductor-vsn
  - r-tidyverse
  - drmaa
