name: sea_snap_development
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - r

  - bamtools
  - bedtools
  - fastqc
  - macs2
  - multiqc
  - picard
  - preseq
  - qualimap
  - rna-seqc
  - rsa
  - rsem
  - rseqc
  - salmon
  - samtools
  - sqlite
  - star
  - subread
  - tpmcalculator
  - trimadap
  - vim
  - rpy2

  - bioconductor-deseq2
  - bioconductor-genomicfeatures
  - bioconductor-annotationdbi
  - bioconductor-org.hs.eg.db # annotation for human
  - bioconductor-org.Mm.eg.db # annotation for mouse
  - bioconductor-tximport
  - bioconductor-goseq
  - bioconductor-apeglm
  - bioconductor-dupradar
  - bioconductor-biomart
  - bioconductor-enrichplot
  - bioconductor-clusterprofiler
  - bioconductor-go.db
  - bioconductor-limma
  - bioconductor-rsamtools
  - bioconductor-rsubread
  - bioconductor-rtracklayer
  - r-blob
  - r-cairo
  - r-cellranger
  - r-cowplot
  - r-crayon
  - r-devtools
  - r-ggplot2
  - r-ggrepel
  - r-ggplotify
  - r-readr
  - r-readxl
  - r-roxygen2
  - r-tidyr
  - r-tidyselect
  - r-testthat
  - r-ashr
  - r-pheatmap
  - r-shiny
  - r-msigdbr
  - r-dplyr
  - r-biocmanager
  - r-xml2
  - r-xopen

  - drmaa
  - snakemake


