name: sea_snap_mapping
channels:
  - conda-forge
  - default
  - bioconda
  - defaults
dependencies:
  - bamtools=2.5.1
  - bedtools=2.29.2
  - biopython=1.76
  - bioconductor-dupradar=1.14.0
  - fastqc=0.11.9
  - gitpython=3.1.2
  - graphviz=2.42.3
  - markdown=3.2.1
  - multiqc=1.8
  - networkx=2.2
  - numpy=1.18.4
  - pandas=1.0.3
  - picard=2.22.4
  - pip=20.1
  - preseq=2.0.3
  - pybigwig=0.3.17
  - pysam=0.15.3
  - python=3.7.6
  - python-irodsclient=0.8.2
  - qualimap=2.2.2d
  - readline=8.0
  - rna-seqc=2.3.5
  - rsem=1.3.3
  - rseqc=3.0.1
  - salmon=1.2.1
  - samtools=1.9
  - snakemake=7.19.1
  - star=2.7.3a
  - subread=2.0.0
  - tpmcalculator=0.0.4
  - trimadap=r9
  - ucsc-bigwigsummary=357
