name: sea_snap_de
channels:
  - conda-forge
  - default
  - bioconda
  - defaults
dependencies:
  - bioconductor-annotate=1.72.0
  - bioconductor-annotationdbi=1.56.1
  - bioconductor-apeglm=1.16.0
  - bioconductor-biobase=2.54.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-biomart=2.50.0
  - bioconductor-clusterprofiler=4.2.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-dupradar=1.24.0
  - bioconductor-genomeinfodb=1.30.0
  - bioconductor-genomicranges=1.46.1
  - bioconductor-go.db=3.14.0
  - bioconductor-goseq=1.46.0
  - bioconductor-iranges=2.28.0
  - bioconductor-keggrest=1.34.0
  - bioconductor-org.hs.eg.db=3.14.0
  - bioconductor-org.mm.eg.db=3.14.0
  - bioconductor-qvalue=2.26.0
  - bioconductor-summarizedexperiment=1.24.0
  - bioconductor-tximport=1.22.0
  - cairo=1.16.0
  - r=4.1
  - r-ashr=2.2_54
  - r-base=4.1.1
  - r-biocmanager=1.30.16
  - r-cairo=1.6
  - r-cowplot
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbplyr=2.1.1
  - r-dt=0.26 
  - r-ggplot2=3.3.5
  - r-ggraph=2.0.5
  - r-ggrepel=0.9.1
  - r-ggridges=0.5.3
  - r-gplots=3.1.1
  - r-gridextra=2.3
  - r-gtools=3.9.2
  - r-igraph=1.2.11
  - r-knitr=1.38
  - r-magrittr=2.0.2
  - r-markdown=1.1
  - r-matrix=1.4_1
  - r-msigdbr=7.4.1
  - r-nlme=3.1_155
  - r-optparse=1.7.1
  - r-patchwork=1.1.1
  - r-pheatmap=1.0.12
  - r-plotly=4.10.1
  - r-plyr=1.8.7
  - r-purrr=0.3.4
  - r-rcolorbrewer=1.1_2
  - r-readr=2.1.2
  - r-restfulr=0.0.13
  - r-rmarkdown=2.19
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-scatterpie=0.1.6
  - r-shiny=1.7.1
  - r-spatial=7.3_15
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-survival=3.3_1
  - r-testthat=3.1.2
  - r-tibble=3.1.6
  - r-tidyr=1.2.0
  - r-writexl=1.4.0
  - readline=8.1
  - snakemake=7.19.1
  - yaml=0.2.4
