name: sea_snap4
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _r-mutex
  - aioeasywebdav
  - aiohttp
  - aiosignal
  - alsa-lib
  - amply
  - appdirs
  - async-timeout
  - atk-1.0
  - attmap
  - attrs
  - azure-common
  - azure-core
  - azure-storage-blob
  - backports
  - backports.functools_lru_cache
  - bamtools
  - bcrypt
  - bedtools
  - binutils_impl_linux-64
  - binutils_linux-64
  - bioconductor-affy
  - bioconductor-affyio
  - bioconductor-annotate
  - bioconductor-annotationdbi
  - bioconductor-apeglm
  - bioconductor-biobase
  - bioconductor-biocfilecache
  - bioconductor-biocgenerics
  - bioconductor-biocio
  - bioconductor-biocparallel
  - bioconductor-biomart
  - bioconductor-biostrings
  - bioconductor-clusterprofiler
  - bioconductor-delayedarray
  - bioconductor-deseq2
  - bioconductor-do.db
  - bioconductor-dose
  - bioconductor-dupradar
  - bioconductor-ebseq
  - bioconductor-enrichplot
  - bioconductor-fgsea
  - bioconductor-genefilter
  - bioconductor-genelendatabase
  - bioconductor-geneplotter
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-ggtree
  - bioconductor-go.db
  - bioconductor-gosemsim
  - bioconductor-goseq
  - bioconductor-iranges
  - bioconductor-keggrest
  - bioconductor-limma
  - bioconductor-matrixgenerics
  - bioconductor-noiseq
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-preprocesscore
  - bioconductor-qvalue
  - bioconductor-rhtslib
  - bioconductor-rsamtools
  - bioconductor-rsubread
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-treeio
  - bioconductor-tximport
  - bioconductor-vsn
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - blas
  - blas-devel
  - blinker
  - blis
  - boost-cpp
  - boto
  - boto3
  - botocore
  - brotli
  - brotli-bin
  - brotlipy
  - bwa
  - bwidget
  - bx-python
  - bzip2
  - c-ares
  - ca-certificates
  - cachetools
  - cairo
  - cairo-cos6-x86_64
  - cairo-devel-cos6-x86_64
  - certifi
  - cffi
  - chardet
  - charset-normalizer
  - click
  - coincbc
  - colorama
  - coloredlogs
  - colormath
  - commonmark
  - configargparse
  - connection_pool
  - cryptography
  - curl
  - cycler
  - dataclasses
  - datrie
  - decorator
  - deeptools
  - deeptoolsintervals
  - defusedxml
  - docutils
  - drmaa
  - dropbox
  - expat
  - fastqc
  - fftw
  - filechunkio
  - filelock
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fontconfig-cos6-x86_64
  - fontconfig-devel-cos6-x86_64
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freetype-cos6-x86_64
  - freetype-devel-cos6-x86_64
  - fribidi
  - frozenlist
  - ftputil
  - future
  - gcc_impl_linux-64
  - gcc_linux-64
  - gdk-pixbuf
  - gettext
  - gfortran_impl_linux-64
  - gfortran_linux-64
  - ghostscript
  - giflib
  - git
  - gitdb
  - gitpython
  - gmp
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - google-cloud-core
  - google-cloud-storage
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - graphite2
  - graphviz
  - greenlet
  - grpcio
  - gsl
  - gtk2
  - gts
  - gxx_impl_linux-64
  - gxx_linux-64
  - harfbuzz
  - htslib
  - httplib2
  - humanfriendly
  - icu
  - idna
  - imagemagick
  - importlib-metadata
  - importlib_resources
  - iniconfig
  - ipython_genutils
  - isodate
  - java-jdk
  - jbig
  - jemalloc
  - jinja2
  - jmespath
  - jpeg
  - jsonschema
  - jupyter_core
  - kernel-headers_linux-64
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgcc
  - libgcc-devel_linux-64
  - libgcc-ng
  - libgd
  - libgfortran-ng
  - libgfortran5
  - libgit2
  - libglib
  - libgomp
  - libiconv
  - libjemalloc
  - liblapack
  - liblapacke
  - libnghttp2
  - libnsl
  - libopenblas
  - libpng
  - libprotobuf
  - librsvg
  - libsodium
  - libssh2
  - libstdcxx-devel_linux-64
  - libstdcxx-ng
  - libtiff
  - libtool
  - libuuid
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - logmuse
  - lz4-c
  - lzo
  - lzstring
  - macs2
  - make
  - markdown
  - markupsafe
  - matplotlib-base
  - more-itertools
  - msgpack-python
  - msrest
  - multidict
  - multiqc
  - munkres
  - mysql-connector-c
  - nbformat
  - ncbi-ngs-sdk
  - ncurses
  - neovim
  - networkx
  - numpy
  - oauth2client
  - oauthlib
  - olefile
  - openblas
  - openjdk
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pandoc
  - pango
  - paramiko
  - pcre
  - pcre2
  - peppy
  - perl
  - perl-app-cpanminus
  - perl-business-isbn
  - perl-business-isbn-data
  - perl-carp
  - perl-constant
  - perl-cpan-meta
  - perl-cpan-meta-requirements
  - perl-cpan-meta-yaml
  - perl-data-dumper
  - perl-encode
  - perl-exporter
  - perl-extutils-cbuilder
  - perl-extutils-makemaker
  - perl-extutils-manifest
  - perl-extutils-parsexs
  - perl-file-path
  - perl-file-temp
  - perl-getopt-long
  - perl-ipc-cmd
  - perl-json-pp
  - perl-locale-maketext-simple
  - perl-mime-base64
  - perl-module-build
  - perl-module-corelist
  - perl-module-load
  - perl-module-load-conditional
  - perl-module-metadata
  - perl-params-check
  - perl-parent
  - perl-perl-ostype
  - perl-scalar-list-utils
  - perl-text-abbrev
  - perl-text-parsewords
  - perl-uri
  - perl-version
  - perl-xml-libxml
  - perl-xml-namespacesupport
  - perl-xml-sax
  - perl-xml-sax-base
  - perl-xsloader
  - picard
  - pillow
  - pip
  - pixman
  - pixman-cos6-x86_64
  - pixman-devel-cos6-x86_64
  - pkg-config
  - plac
  - plotly
  - pluggy
  - ply
  - preseq
  - prettytable
  - protobuf
  - psutil
  - pulp
  - py
  - py2bit
  - pyasn1
  - pyasn1-modules
  - pybigwig
  - pycparser
  - pygments
  - pygraphviz
  - pyjwt
  - pynacl
  - pynvim
  - pyopenssl
  - pyparsing
  - pyrsistent
  - pysam
  - pysftp
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-irodsclient
  - python-lzo
  - python-tzdata
  - python_abi
  - pytz
  - pytz-deprecation-shim
  - pyu2f
  - pyyaml
  - qualimap
  - r
  - r-ape
  - r-aplot
  - r-ashr
  - r-askpass
  - r-assertthat
  - r-babelgene
  - r-backports
  - r-base
  - r-base64enc
  - r-bbmle
  - r-bdsmatrix
  - r-bh
  - r-biasedurn
  - r-bibtex
  - r-biocmanager
  - r-bit
  - r-bit64
  - r-bitops
  - r-blob
  - r-blockmodeling
  - r-boot
  - r-brew
  - r-brio
  - r-cachem
  - r-cairo
  - r-callr
  - r-catools
  - r-cellranger
  - r-class
  - r-cli
  - r-clipr
  - r-cluster
  - r-coda
  - r-codetools
  - r-colorspace
  - r-commonmark
  - r-covr
  - r-cowplot
  - r-cpp11
  - r-crayon
  - r-credentials
  - r-crosstalk
  - r-curl
  - r-data.table
  - r-dbi
  - r-dbplyr
  - r-desc
  - r-devtools
  - r-diffobj
  - r-digest
  - r-doparallel
  - r-dorng
  - r-downloader
  - r-dplyr
  - r-dt
  - r-ellipsis
  - r-emdbook
  - r-etrunct
  - r-evaluate
  - r-fansi
  - r-farver
  - r-fastmap
  - r-fastmatch
  - r-filelock
  - r-foreach
  - r-foreign
  - r-formatr
  - r-fs
  - r-futile.logger
  - r-futile.options
  - r-generics
  - r-gert
  - r-getopt
  - r-ggforce
  - r-ggfun
  - r-ggplot2
  - r-ggplotify
  - r-ggraph
  - r-ggrepel
  - r-gh
  - r-git2r
  - r-gitcreds
  - r-glue
  - r-gplots
  - r-graphlayouts
  - r-gridextra
  - r-gridgraphics
  - r-gtable
  - r-gtools
  - r-highr
  - r-hms
  - r-htmltools
  - r-htmlwidgets
  - r-httr
  - r-igraph
  - r-ini
  - r-invgamma
  - r-irlba
  - r-isoband
  - r-iterators
  - r-jquerylib
  - r-jsonlite
  - r-kernsmooth
  - r-knitr
  - r-labeling
  - r-lambda.r
  - r-later
  - r-lattice
  - r-lazyeval
  - r-lifecycle
  - r-locfit
  - r-magrittr
  - r-mass
  - r-matrix
  - r-matrixstats
  - r-memoise
  - r-mgcv
  - r-mime
  - r-mixsqp
  - r-msigdbr
  - r-munsell
  - r-mvtnorm
  - r-nlme
  - r-nnet
  - r-numderiv
  - r-openssl
  - r-optparse
  - r-pander
  - r-patchwork
  - r-pheatmap
  - r-pillar
  - r-pkgbuild
  - r-pkgconfig
  - r-pkgload
  - r-pkgmaker
  - r-plogr
  - r-plyr
  - r-png
  - r-polyclip
  - r-praise
  - r-prettyunits
  - r-processx
  - r-progress
  - r-promises
  - r-ps
  - r-purrr
  - r-r6
  - r-rappdirs
  - r-rcmdcheck
  - r-rcolorbrewer
  - r-rcpp
  - r-rcpparmadillo
  - r-rcppeigen
  - r-rcppnumerical
  - r-rcurl
  - r-readr
  - r-readxl
  - r-recommended
  - r-registry
  - r-rematch
  - r-rematch2
  - r-remotes
  - r-reshape2
  - r-restfulr
  - r-rex
  - r-rjson
  - r-rlang
  - r-rmarkdown
  - r-rngtools
  - r-roxygen2
  - r-rpart
  - r-rprojroot
  - r-rsqlite
  - r-rstudioapi
  - r-rsvg
  - r-rvcheck
  - r-rversions
  - r-scales
  - r-scatterpie
  - r-sessioninfo
  - r-shadowtext
  - r-snow
  - r-spatial
  - r-squarem
  - r-stringi
  - r-stringr
  - r-survival
  - r-sys
  - r-testthat
  - r-tibble
  - r-tidygraph
  - r-tidyr
  - r-tidyselect
  - r-tidytree
  - r-tinytex
  - r-truncnorm
  - r-tweenr
  - r-tzdb
  - r-usethis
  - r-utf8
  - r-vctrs
  - r-viridis
  - r-viridislite
  - r-vroom
  - r-waldo
  - r-whisker
  - r-withr
  - r-writexl
  - r-xfun
  - r-xml
  - r-xml2
  - r-xopen
  - r-xtable
  - r-yaml
  - r-yulab.utils
  - r-zeallot
  - r-zip
  - ratelimiter
  - readline
  - requests
  - requests-oauthlib
  - retrying
  - rich
  - rna-seqc
  - rpy2
  - rsa
  - rsem
  - rseqc
  - s3transfer
  - salmon
  - samtools
  - scipy
  - sed
  - setuptools
  - simplegeneric
  - simplejson
  - six
  - slacker
  - smart_open
  - smmap
  - snakemake
  - snakemake-minimal
  - spectra
  - sqlite
  - star
  - stone
  - stopit
  - subread
  - sysroot_linux-64
  - tabulate
  - tbb
  - tenacity
  - tk
  - tktable
  - toml
  - tomli
  - toposort
  - tornado
  - tpmcalculator
  - traitlets
  - trimadap
  - typing-extensions
  - typing_extensions
  - tzdata
  - tzlocal
  - ubiquerg
  - ucsc-bigwigsummary
  - unicodedata2
  - uritemplate
  - urllib3
  - veracitools
  - vim
  - wcwidth
  - wheel
  - wrapt
  - xmlrunner
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-libxt
  - xorg-libxtst
  - xorg-recordproto
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - yarl
  - yte
  - zipp
  - zlib
  - zstd
