# Exported files

```{r export_files_setup}
require(dplyr)
require(writexl)
require(purrr)
require(DESeq2)
require(edgeR)
require(pander)

export_dir <- config$report$snippet_parameters$Export_files$export_dir
if(is.null(export_dir)) {
  export_dir <- "export_files"
  warning("config report:snippet_parameters:Export_files:export_dir not found, using export_files/")
}

dir.create(export_dir, showWarnings=FALSE)

counts_f        <- file.path(export_dir, "counts.xlsx")
gene_expr_res_f <- file.path(export_dir, "differential_expression_results.xlsx")
covariate_f     <- file.path(export_dir, "covariate_file.xlsx")
tmod_annotation_f <- file.path(export_dir, "gene_set_annotation_significant.xlsx")
```





```{r export_files_do}
## export raw counts
ds_ft <- file_tab %>% filter(step == "DESeq2")

ds <- file_tab %>% filter(extension == "deseq2.rds") %>% 
  pull(filename) %>% readRDS

rld <- file_tab %>% filter(extension == "rld.blind.rds") %>% 
  pull(filename) %>% readRDS

covar <- colData(rld) %>% as.data.frame()

annot <- file_tab %>% filter(step=="annotation" & extension == "rds") %>% 
  pull(filename) %>% readRDS %>% slice(match(rownames(rld), PrimaryID))

write_xlsx(list("Raw counts"=as.data.frame(counts(ds)) %>% rownames_to_column("PrimaryID"), 
                "RLD"=as.data.frame(assay(rld)) %>% rownames_to_column("PrimaryID"),
                "Annotation"=annot,
                "Covariates"=covar),
           path=counts_f)

## export DE analysis data
contrasts <- file_tab %>% filter(step=="contrast" & extension=="rds") %>%
  mutate(ID=gsub(".*_", "", contrast)) %>%
  arrange(ID)

files <- set_names(contrasts[["filename"]], contrasts[["contrast"]])
gene_expr_res <- map(files, readRDS) %>% map(as.data.frame) %>%
  map(rownames_to_column, "PrimaryID") %>% map(arrange, padj)

annotation <- file_tab %>% filter(step=="annotation" & extension=="rds") %>%
 pull("filename") %>% readRDS()

write_xlsx(c(list(Annotation=annotation), gene_expr_res, list(Covariates=covar)), 
  path=gene_expr_res_f)

write_xlsx(list(Covariates=covar), path=covariate_f)

## Export tmod results
tmod_ft <- file_tab %>% filter(step == "tmod" & extension == "xlsx") %>%
  mutate(ID=gsub(".*_", "", contrast)) %>% arrange(ID)
for(f in tmod_ft %>% pull(filename)) {
  file.copy(f, export_dir)
}

## Export module annotations

tmod_res <- file_tab %>% dplyr::filter(step == "tmod" & extension == "rds") %>% pull(filename) %>% map(readRDS)

tmod_db_ids <- tmod_res %>% map(names) %>% unlist %>% unique %>% purrr::set_names()

tmod_dbs <- file_tab %>% filter(step == "tmod_dbs" & extension == "rds") %>% pull(filename) %>% readRDS
tmod_map <- file_tab %>% filter(step == "tmod_dbs" & extension == "mapping.rds") %>% pull(filename) %>% readRDS
annot    <- file_tab %>% filter(step == "annotation" & extension == "rds") %>% pull(filename) %>% readRDS

tmod_mods <- map(tmod_db_ids, ~ {
  .id <- .x
  ids <- tmod_res %>% map(`[[`, .id) %>% unlist(recursive=FALSE) %>% map(~ .x %>% dplyr::filter(adj.P.Val < 0.05)) %>% map(`[[`, "ID") %>% unlist %>% unique

  if(length(ids) < 1) {
    return(NULL)
  }

  db <- tmod_dbs[[.id]]$dbobj
  db <- db[ ids ]
  mapping <- tmod_map$maps[[ tmod_map$dbs[.id] ]]

  df <- tmod2DataFrame(db)

  # translate the gene IDs to the gene IDs (or, preferably, symbols) of the
  # project
  genes <- getModuleMembers(df$module_id, mset=db)

  genes <- map(genes, ~ names(mapping)[ mapping %in% .x ])

  if("SYMBOL" %in% colnames(annot)) {
    genes <- map(genes, ~ {
      sym <- annot$SYMBOL[ match(.x, annot$PrimaryID) ]
      ifelse(is.na(sym), genes, sym)
    })
  }
  genes <- map_chr(genes, paste, collapse=",")
  df$feature_id <- genes
  return(df)
})

tmod_mods <- tmod_mods[!map_lgl(tmod_mods, is.null)]
write_xlsx(tmod_mods, path=tmod_annotation_f)


```

**Table.** Following files have been exported to the `r export_dir` directory.

```{r export_files_filetab,results="markdown"}
.f <- c(covariate_f, counts_f, gene_expr_res_f)
export_ft <- data.frame(
  Description=c(
    "Covariate file",
    "Raw counts, log CPM and rlog counts",
    "Results of differential expression analysis for all contrasts"),
  File=sprintf("[%s](%s)", basename(.f), .f),
  stringsAsFactors=FALSE)
     
export_ft_2 <- tmod_ft %>%
  mutate(Description=sprintf("Results of gene enrichment analysis with tmod for contrast %s", contrast),
         File=sprintf("[%s](%s)", basename(filename), file.path(export_dir, basename(filename)))) %>%
  dplyr::select(Description, File)

export_ft <- rbind(export_ft, export_ft_2)
pander(export_ft)
```



