#---------------------------------------- general pipeline parameters
pipeline_param:
  out_path_pattern: \S+
  log_path_pattern: \S+
  in_path_pattern: \S+

  cellranger_executable: \S+
  feature_ref: .*
  test_config: {__opt__: [true, false]}

#---------------------------------------- organism annotation
organism_defaults:
  __opt__: [null, \S*]

#---------------------------------------- parameters for rules
rule_options:
  cellranger_count:
    cmd_opt: .*
  velocyto_run:
    cmd_opt: .*
        
#---------------------------------------- configuration for export
export:
  blueprint:
    __opt__:
      - null
      - file: \S*
        command: .+
  path_pattern: [\S+]
  __any__:
    - __opt__:
        - files:
            __any_other__:
              step: \S+
              extension: \S+
              log: {__opt__: [true, false]}
        - dir:
            __any_other__:
              step: \S+
              log: {__opt__: [true, false]}
      __any_other__:
        compress:
          __opt__: [zip, tar]




