#---------------------------------------- general pipeline parameters
pipeline_param:
  # adjust pattern of stored files
  out_path_pattern: sc_analysis/{step}/{sample}.{mate}/out/{step}.{sample}.{mate}.{extension}
  log_path_pattern: sc_analysis/{step}/{sample}.{mate}/report/{step}.{sample}.{mate}.{extension}
  in_path_pattern: ../input/{sample}/{sample}.{mate}

  test_config: true

#---------------------------------------- organism annotation
organism_defaults: null

#---------------------------------------- parameters for rules
rule_options:
  cellranger_count:
    cmd_opt: "--jobmode sge --maxjobs=100 --jobinterval=1000"
  velocyto_run:
    cmd_opt: "--samtools-memory 4000 -@ 4"

#---------------------------------------- parameters for the jupyter notebook
report:
  snippet_parameters: {}
  defaults: {}
  report_snippets: []

#---------------------------------------- configuration for export
export:
  blueprint:
    file: SODAR_export_blueprint.txt
    command: |
      imkdir -p $(dirname {dest} )
      irsync -a -K {src} i:{dest}
  path_pattern:
    - __SODAR__/{sample}/{GENOME}/%Y_%m_%d/{files:ngs_mapping:out}/{step}/out/{step}.{sample}.{extension}
    - __SODAR__/{sample}/{GENOME}/%Y_%m_%d/{files:ngs_mapping:rep}/{step}/report.zip
    - __SODAR__/{sample}/{GENOME}/%Y_%m_%d/{files:gene_expression_quantification}/{step}/out/{step}.{sample}.{extension}
  ngs_mapping_out:
    - files: {step: star, extension: bam}
  ngs_mapping_rep:
    - dir: {step: star, log: true}
      compress: zip
  gene_expression_quantification:
    - files: {step: star, extension: gene_counts.tab}
    - files: {step: salmon, extension: sf}
