#---------------------------------------- general pipeline parameters
pipeline_param:
  # adjust pattern of stored files
  out_path_pattern: sc_analysis/{step}/{sample}.{mate}/out/{step}.{sample}.{mate}.{extension}
  log_path_pattern: sc_analysis/{step}/{sample}.{mate}/report/{step}.{sample}.{mate}.{extension}
  in_path_pattern: ../input/{sample}/{sample}.{mate}

  test_config: true
  report_snippets: ""

  feature_ref: ""

  # adjust which results are produced
  produce_results:
    - cellranger
    - velocyto

  input_choice:
    velocyto:
      - cellranger_count
      - cellranger_aggr

#---------------------------------------- organism annotation
organism_defaults: null

#---------------------------------------- parameters for rules
rule_options:
  cellranger_count:
    cmd_opt: ""   # "--jobmode sge --maxjobs=100 --jobinterval=1000"
  velocyto_run:
    cmd_opt: "--samtools-memory 4000 -@ 4"

#---------------------------------------- parameters for the jupyter notebook
jupyter_notebook:
  snippet_parameters: {}
  defaults: {}
  report_snippets:
    - load_matrix.ipynb
    - filter_and_normalize.ipynb
    - plot_dim_reduction.ipynb
    - ranking_and_marker_genes.ipynb
    - compute_velocities.ipynb

#---------------------------------------- configuration for export
export:
  blueprint:
    file: SODAR_export_blueprint.txt
    command: |
      imkdir -p $(dirname {dest} )
      irsync -a -K {src} i:{dest}
  path_pattern:
    - __SODAR__/{sample}/{files:cellranger}
    - __SODAR__/{sample}/cellranger/{files:cellranger_logs}.tgz
    - __SODAR__/{sample}/{files:velocyto}
  cellranger:
    - dir: {step: cellranger_count, mate: all_mates}
      suffix: outdir/outdir/outs
      compress: tar
      compress_list: [analysis, raw_feature_bc_matrix, filtered_feature_bc_matrix]
  cellranger_logs:
    - dir: {step: cellranger_count, mate: all_mates}
      suffix: outdir/outdir
      compress: tar
      exclude: [outdir/outs, outdir/SC_RNA_COUNTER_CS]
  velocyto:
    - files: {step: velocyto_run, extension: loom, mate: all_mates}