### Results table

```{r}
#----- import packages
library(DT)
library(magrittr)

#----- load results
res   <- readRDS("{{contrast-rds-{{ENTRY_ID}}}}")
annot <- readRDS(subset(file_tab, step=="annotation" & extension=="rds" & contrast=="all")$filename)
results_table <- as.data.frame(res) 
results_table <- merge(annot, results_table, by.x="PrimaryID", by.y=0)

ids <- is.element(colnames(results_table), c("entrez", "symbol"))
results_table <- results_table[,c(which(ids), which(!ids))]
#
#----- filter results
qval.thr <- config$report$snippet_parameters$contrast$filter_results$qval
results_table <- subset(results_table, padj < qval.thr)
```


An interactive data table of the contrast results for {{ENTRY_NAME}}. Only
results with adjusted p value smaller than 
`r format.pval(qval.thr)`
are included (total
`r nrow(results_table)` results shown).

```{r table_{{ENTRY_ID}}}

#----- interactive table
datatable(results_table, extensions=c('Buttons','FixedColumns'), escape=F,
          options = list(scrollX=TRUE, fixedColumns=list(leftColumns=3), dom='Bfrtip', buttons='csv')) %>%
  formatRound('baseMean', 3) %>%
  formatRound('log2FoldChange', 3) %>%
  formatRound('lfcSE', 3) %>%
  formatRound('stat', 3) %>%
  formatRound('pvalue', 4) %>%
  formatRound('padj', 4)
```

